name: Backend CI

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'migrations/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'migrations/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
          check-latest: true
          cache: true

      - name: Verify formatting
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "The following files need gofmt:"
            echo "$fmt_out"
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Run unit tests
        run: go test ./...
